### ISSUE TITLE
Korjaa ruma readme??

### ISSUE THREAD

**Issue by KasperiP** [AnttiMK/KarhuVelocity#5]
<style> .header { width: 250px; text-align: center; margin: 0 auto; padding: 0; margin-bottom: 1rem; font-size: 2rem; font-weight: bold; } </style>

**Comment by AnttiMK** [comment]
https://github.com/AnttiMK/KarhuVelocity/commit/f340cb2bafb53de611001af164b47e1788a14b48

**Comment by AnttiMK** [comment]
https://github.com/AnttiMK/KarhuVelocity/commit/f340cb2bafb53de611001af164b47e1788a14b48
